DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS files CASCADE;


CREATE TABLE admins (
	id SERIAL PRIMARY KEY,
	subdomain TEXT NOT NULL,
	email TEXT NOT NULL,
	pw_hash TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	UNIQUE (email),
	UNIQUE (subdomain)
);

CREATE TABLE clients (
	id SERIAL PRIMARY KEY,
	subdomain TEXT NOT NULL REFERENCES admins(subdomain),
	email TEXT NOT NULL,
	pw_hash TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	UNIQUE (subdomain, email)
);

CREATE TABLE projects (
	id SERIAL PRIMARY KEY,
	admin_id INTEGER NOT NULL REFERENCES admins(id),
	title TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE files (
	id SERIAL PRIMARY KEY,
	admin_id INTEGER NOT NULL REFERENCES admins(id),
	project_id INTEGER NOT NULL REFERENCES projects(id),
	file_name TEXT,
	file_type TEXT,
	file_url TEXT,
	size_bytes INTEGER,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
