DROP TABLE IF EXISTS orgs CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS files CASCADE;

CREATE TABLE orgs (
	id SERIAL PRIMARY KEY,
	title VARCHAR NOT NULL
);

CREATE TABLE accounts (
	id SERIAL PRIMARY KEY,
	org_id INTEGER NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
	email VARCHAR NOT NULL,
	pw_hash VARCHAR NOT NULL,
	account_role VARCHAR NOT NULL CHECK (account_role IN ('admin', 'client')),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

	UNIQUE (org_id, email)
);

CREATE TABLE admins (
	id INTEGER PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE
);

CREATE TABLE clients (
	id INTEGER PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE
);

CREATE TABLE projects (
	id SERIAL PRIMARY KEY,
	org_id INTEGER NOT NULL REFERENCES orgs(id),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE files (
	id SERIAL PRIMARY KEY,
	org_id INTEGER NOT NULL REFERENCES orgs(id),
	project_id INTEGER NOT NULL REFERENCES projects(id),
	file_name VARCHAR,
	file_type VARCHAR,
	url VARCHAR,
	size_bytes INTEGER,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
